### ISSUE TITLE
Reveal_in_os_explorer_active not show

### ISSUE THREAD

**Issue by windsonR** [AnWeber/reveal-button#2]
https://github.com/AnWeber/reveal-button/blob/0c3924b0632954ce19a780c844c6b84c87375050/package.json#L90

This config looks like not right.

**Comment by AnWeber** [comment]
I was a bit too creative with the naming, but it seems to work. What is not working?

![reveal](https://user-images.githubusercontent.com/13434739/164031944-eb44e054-1e26-4969-88f6-88d4fa0056af.gif)

**Comment by AnWeber** [comment]
Sorry. Yes, there was an error a few lines below. I have fixed it and am making a new version. Thanks.
